services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - path: ./.postgres.env
        required: true
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - personal_finances_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal_finances_app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - personal_finances_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - path: ./.pgadmin.env
        required: true
    restart: always
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - personal_finances_network

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - personal_finances_network

networks:
  personal_finances_network:
    name: personal_finances_network
    driver: bridge